/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 6478b24dc399ae0df683f3d390117bc7)
interface __BaseEnv_Env {
	DAILY_IMAGES: R2Bucket;
	DB: D1Database;
	BROWSER: BrowserRun;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	EMAIL_FROM: "Haiku-ly <daily@haikuly.fyi>";
	EMAIL_REPLY_TO: "zhiguoinusa@gmail.com";
	PUBLIC_BASE_URL: "https://haikuly.fyi";
	MAX_DAILY_RECIPIENTS: "90";
	MAX_DAILY_CONFIRMATIONS: "10";
	DEEPSEEK_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_FROM" | "EMAIL_REPLY_TO" | "PUBLIC_BASE_URL" | "MAX_DAILY_RECIPIENTS" | "MAX_DAILY_CONFIRMATIONS" | "DEEPSEEK_API_KEY">> {}
}
